# Import Modules and Config

In [1]:
import data_load
import clustering_model
import regression_model
%load_ext autoreload
%autoreload 2

In [15]:
UPDATE_DATA_LOAD = False
UPDATE_CLUSTERING_MODEL = True
UPDATE_REGRESSION_MODEL = True

# Data Load

In [16]:
basic_df = data_load.load_basic_data(
    selected_symbols=20, 
    max_date_added_year=2020, 
    min_last_update_year=2023, 
    min_market_pairs=6, 
    update=UPDATE_DATA_LOAD
)
print(basic_df.shape)
basic_df.head()

(19, 19)

,id,name,symbol,slug,tags,cmcRank,marketPairCount,circulatingSupply,selfReportedCirculatingSupply,totalSupply,maxSupply,isActive,lastUpdated,dateAdded,quotes,isAudited,badges,auditInfoList,platform
0,1,Bitcoin,BTC,bitcoin,"['mineable', 'pow', 'sha-256', 'store-of-value...",1,10543,1.953815e+07,0,1.953815e+07,2.100000e+07,1,2023-11-10T06:34:00.000Z,2010-07-13T00:00:00.000Z,"[{'name': 'USD', 'price': 36621.182092247414, ...",False,"[1, 5]",NaN,NaN
1,1027,Ethereum,ETH,ethereum,"['pos', 'smart-contracts', 'ethereum-ecosystem...",2,7745,1.202636e+08,0,1.202636e+08,NaN,1,2023-11-10T06:34:00.000Z,2015-08-07T00:00:00.000Z,"[{'name': 'USD', 'price': 2110.4244127662914, ...",False,"[1, 3, 5]",[],NaN
2,825,Tether USDt,USDT,tether,"['payments', 'stablecoin', 'asset-backed-stabl...",3,65388,8.651725e+10,0,8.962366e+10,NaN,1,2023-11-10T06:33:00.000Z,2015-02-25T00:00:00.000Z,"[{'name': 'USD', 'price': 1.0000804496610904, ...",True,[],"[{'coinId': '825', 'auditor': 'CertiK', 'audit...","{'id': 1, 'name': 'Ethereum', 'symbol': 'ETH',..."
3,1839,BNB,BNB,bnb,"['marketplace', 'centralized-exchange', 'payme...",4,1752,1.517021e+08,0,1.517021e+08,NaN,1,2023-11-10T06:33:00.000Z,2017-07-25T00:00:00.000Z,"[{'name': 'USD', 'price': 254.62419901858183, ...",True,[3],"[{'coinId': '1839', 'auditor': 'CertiK', 'audi...",NaN
4,52,XRP,XRP,xrp,"['medium-of-exchange', 'enterprise-solutions',...",5,1136,5.365277e+10,0,9.998824e+10,1.000000e+11,1,2023-11-10T06:34:00.000Z,2013-08-04T00:00:00.000Z,"[{'name': 'USD', 'price': 0.6621545512486472, ...",True,[],"[{'coinId': '52', 'auditor': 'CertiK', 'auditS...",NaN

In [17]:
symbols_list = basic_df["symbol"].to_list()
historical_df = data_load.load_historical_data(
    symbols_list,
    update=UPDATE_DATA_LOAD
)
print(historical_df.shape)
historical_df.head()

(42819, 10)

,symbol,date,open,high,low,close,avg,return,volume,marketcap
0,BTC,2023-11-09,35633.634394,37926.256797,35592.103252,36693.123634,36163.379014,0.029733,3.776267e+10,7.169024e+11
1,BTC,2023-11-08,35419.476717,35994.416531,35147.800805,35655.276081,35537.376399,0.006657,1.729539e+10,6.965953e+11
2,BTC,2023-11-07,35047.793633,35892.416370,34545.815095,35443.561361,35245.677497,0.011292,1.883474e+10,6.924256e+11
3,BTC,2023-11-06,35044.789919,35286.026827,34765.364847,35037.369441,35041.079680,-0.000212,1.269344e+10,6.844605e+11
4,BTC,2023-11-05,35090.013021,35340.339719,34594.242577,35049.355924,35069.684473,-0.001159,1.241274e+10,6.846677e+11

In [18]:
selected_df = data_load.load_selected_data(
    historical_df, 
    selected_days=1460, 
    end_date="2023-10-10", 
    update=UPDATE_DATA_LOAD
)
print(selected_df.shape)
selected_df.head()

(17520, 10)

,symbol,date,open,high,low,close,avg,return,volume,marketcap
0,BTC,2023-10-10,27589.201102,27715.848347,27301.655078,27391.019517,27490.110310,-0.007183,9.973351e+09,5.343984e+11
1,BTC,2023-10-09,27934.472162,27989.470902,27302.561919,27583.678595,27759.075379,-0.012558,1.200767e+10,5.381279e+11
2,BTC,2023-10-08,27971.678107,28102.170391,27740.663024,27935.089581,27953.383844,-0.001308,7.916875e+09,5.449575e+11
3,BTC,2023-10-07,27946.781633,28028.092087,27870.423458,27968.838871,27957.810252,0.000789,6.553044e+09,5.455899e+11
4,BTC,2023-10-06,27412.122424,28252.537570,27215.552446,27946.596780,27679.359602,0.019498,1.349239e+10,5.451267e+11

# Clustering Model

In [19]:
# TODO: Add a KPI to measure how much the model worked

In [20]:
return_df = clustering_model.load_return_data(
    selected_df, 
    update=UPDATE_CLUSTERING_MODEL
)
print(return_df.shape)
return_df.head()

(1460, 12)

,ADA,BCH,BNB,BTC,DOGE,ETH,LTC,MATIC,TRX,USDC,USDT,XRP
0,0.000053,0.010657,0.033728,0.002512,0.005015,-0.009354,-0.007473,-0.020521,-0.016072,-0.004148,-0.007881,0.007657
1,0.019357,-0.004072,0.060925,-0.001907,0.046538,0.006711,0.013802,-0.036510,0.025739,0.000226,0.000532,0.016974
2,0.011243,0.020693,0.008273,0.006472,0.039529,0.027097,0.004535,0.015636,0.036808,-0.000418,-0.000642,0.068065
3,-0.048566,-0.024983,0.006446,-0.020074,-0.014151,-0.029795,-0.036190,-0.058215,-0.058775,0.001337,-0.000194,-0.026097
4,-0.025635,-0.020902,-0.036556,-0.019153,0.039411,-0.029393,-0.037528,-0.032846,-0.028902,0.000364,0.002089,-0.014730

In [21]:
clusters_df = clustering_model.load_clusters_data(
    return_df, 
    UPDATE_CLUSTERING_MODEL
)
clusters_number = clusters_df['cluster'].unique().shape[0]
print(clusters_number, 'clusters')
clusters_df.head()

3 clusters

  symbol  cluster
0   DOGE        0
1    ADA        1
2    BCH        1
3    BNB        1
4    BTC        1

# Regression Model

In [22]:
# TODO: Use ANN models
# TODO: Add financial indexes to regression model
# TODO: Add more regression models (LogisticRegression(), SVC(kernel='poly', probability=True), XGBClassifier(), etc)
# TODO: Grid search over parameters

In [23]:
regression_df = regression_model.load_regression_data(
    selected_df, 
    clusters_df, 
    future_days=30, 
    update=UPDATE_REGRESSION_MODEL
)
print(regression_df.shape)
regression_df.head()

(17520, 45)

,symbol,date,open,high,low,close,avg,return,volume,marketcap,...,symbol_MATIC,symbol_TRX,symbol_USDC,symbol_USDT,symbol_XRP,cluster_0,cluster_1,cluster_2,future_return,future_risk
0,BTC,2023-10-10,27589.201102,27715.848347,27301.655078,27391.019517,27490.110310,-0.007183,9.973351e+09,5.343984e+11,...,False,False,False,False,False,False,True,False,NaN,NaN
1,BTC,2023-10-09,27934.472162,27989.470902,27302.561919,27583.678595,27759.075379,-0.012558,1.200767e+10,5.381279e+11,...,False,False,False,False,False,False,True,False,NaN,NaN
2,BTC,2023-10-08,27971.678107,28102.170391,27740.663024,27935.089581,27953.383844,-0.001308,7.916875e+09,5.449575e+11,...,False,False,False,False,False,False,True,False,NaN,NaN
3,BTC,2023-10-07,27946.781633,28028.092087,27870.423458,27968.838871,27957.810252,0.000789,6.553044e+09,5.455899e+11,...,False,False,False,False,False,False,True,False,NaN,NaN
4,BTC,2023-10-06,27412.122424,28252.537570,27215.552446,27946.596780,27679.359602,0.019498,1.349239e+10,5.451267e+11,...,False,False,False,False,False,False,True,False,NaN,NaN

In [24]:
# regression_df.plot.scatter(x='close', y='future_return')

In [25]:
prediction_df = regression_model.load_prediction_data(
    regression_df, 
    model='random_forest_regressor', 
    update=UPDATE_REGRESSION_MODEL
)
print(prediction_df.shape)
prediction_df.head()

(12, 45)

,symbol,date,open,high,low,close,avg,return,volume,marketcap,...,symbol_MATIC,symbol_TRX,symbol_USDC,symbol_USDT,symbol_XRP,cluster_0,cluster_1,cluster_2,future_return,future_risk
0,ADA,2023-10-10,0.251631,0.253101,0.247501,0.249141,0.250386,-0.009894,1.101835e+08,8.757862e+09,...,False,False,False,False,False,False,True,False,-0.061398,0.005115
1,BCH,2023-10-10,218.438845,219.819033,210.992026,212.499744,215.469294,-0.027189,1.489568e+08,4.149692e+09,...,False,False,False,False,False,False,True,False,0.425806,0.014923
2,BNB,2023-10-10,205.750092,210.454291,205.750092,208.576880,207.163486,0.013739,4.419594e+08,3.208859e+10,...,False,False,False,False,False,False,True,False,-0.089672,0.009542
3,BTC,2023-10-10,27589.201102,27715.848347,27301.655078,27391.019517,27490.110310,-0.007183,9.973351e+09,5.343984e+11,...,False,False,False,False,False,False,True,False,0.090191,0.008380
4,DOGE,2023-10-10,0.058779,0.059204,0.058608,0.059025,0.058902,0.004183,1.233113e+08,8.343727e+09,...,False,False,False,False,False,True,False,False,0.150304,0.000956

# Portfolio Selection

In [ ]:
# TODO: Use clustering models
# TODO: Add CAPM Model
# TODO: Add Black-Litterman allocation?
# TODO: long and short? weight_bounds=(-1, 1)

In [ ]:
close_df = selected_df[["date", "symbol", "close"]].copy()
close_df = close_df.pivot(index="date", columns="symbol")
close_df = close_df["close"]
close_df.columns.name = None
close_df

In [ ]:
# Mean Variance

from pypfopt.expected_returns import mean_historical_return
from pypfopt.risk_models import CovarianceShrinkage
from pypfopt.efficient_frontier import EfficientFrontier

m = mean_historical_return(close_df)  # mu = expected_returns.mean_historical_return(df)
s = CovarianceShrinkage(close_df).ledoit_wolf()  # S = risk_models.sample_cov(df)
ef = EfficientFrontier(m, s)
weights = ef.max_sharpe()
cleaned_weights = ef.clean_weights()

ef.portfolio_performance(verbose=True)
print(dict(cleaned_weights))

In [ ]:
# Hierarchical Risk Parity

from pypfopt import HRPOpt

returns = close_df.pct_change().dropna()
hrp = HRPOpt(returns)
weights = hrp.optimize()
cleaned_weights = hrp.clean_weights()

hrp.portfolio_performance(verbose=True)
print(dict(cleaned_weights))

In [ ]:
# mCVAR

from pypfopt.efficient_frontier import EfficientCVaR

m = mean_historical_return(close_df)
s = close_df.cov()
ef_cvar = EfficientCVaR(m, s)
cvar_weights = ef_cvar.min_cvar()
cleaned_weights = ef_cvar.clean_weights()

ef_cvar.portfolio_performance(verbose=True)
print(dict(cleaned_weights))