# Import Modules and Config

In [2]:
import data_load
import clustering_model
import regression_model
%load_ext autoreload
%autoreload 2

In [3]:
UPDATE_DATA_LOAD = False
UPDATE_CLUSTERING_MODEL = True
UPDATE_REGRESSION_MODEL = True

# Data Load

In [4]:
basic_data = data_load.load_basic_data(selected_symbols=10, max_date_added_year=2020, min_last_update_year=2023, min_market_pairs=6, update=UPDATE_DATA_LOAD)
print(basic_data.shape)
basic_data.head()

(10, 18)

,id,name,symbol,slug,tags,cmcRank,marketPairCount,circulatingSupply,selfReportedCirculatingSupply,totalSupply,maxSupply,isActive,lastUpdated,dateAdded,quotes,isAudited,auditInfoList,platform
0,1,Bitcoin,BTC,bitcoin,"['mineable', 'pow', 'sha-256', 'store-of-value...",1,10443,1.947698e+07,0,1.947698e+07,2.100000e+07,1,2023-09-05T11:50:00.000Z,2010-07-13T00:00:00.000Z,"[{'name': 'USD', 'price': 25757.514047797253, ...",False,NaN,NaN
1,1027,Ethereum,ETH,ethereum,"['pos', 'smart-contracts', 'ethereum-ecosystem...",2,7335,1.202182e+08,0,1.202182e+08,NaN,1,2023-09-05T11:50:00.000Z,2015-08-07T00:00:00.000Z,"[{'name': 'USD', 'price': 1633.7776828205042, ...",False,[],NaN
2,825,Tether USDt,USDT,tether,"['payments', 'stablecoin', 'asset-backed-stabl...",3,61371,8.290552e+10,0,8.543720e+10,NaN,1,2023-09-05T11:50:00.000Z,2015-02-25T00:00:00.000Z,"[{'name': 'USD', 'price': 0.9993057957558301, ...",True,"[{'coinId': '825', 'auditor': 'CertiK', 'audit...","{'id': 1, 'name': 'Ethereum', 'symbol': 'ETH',..."
3,1839,BNB,BNB,bnb,"['marketplace', 'centralized-exchange', 'payme...",4,1606,1.538499e+08,0,1.538499e+08,NaN,1,2023-09-05T11:50:00.000Z,2017-07-25T00:00:00.000Z,"[{'name': 'USD', 'price': 215.04910221058182, ...",True,"[{'coinId': '1839', 'auditor': 'CertiK', 'audi...",NaN
4,52,XRP,XRP,xrp,"['medium-of-exchange', 'enterprise-solutions',...",5,1061,5.297770e+10,0,9.998846e+10,1.000000e+11,1,2023-09-05T11:50:00.000Z,2013-08-04T00:00:00.000Z,"[{'name': 'USD', 'price': 0.5033568695749688, ...",True,"[{'coinId': '52', 'auditor': 'CertiK', 'auditS...",NaN

In [5]:
symbols_list = basic_data["symbol"].to_list()
historical_data = data_load.load_historical_data(symbols_list, update=UPDATE_DATA_LOAD)
print(historical_data.shape)
historical_data.head()

(26217, 10)

,symbol,date,open,high,low,close,avg,return,volume,marketcap
0,BTC,2023-09-04,25968.170133,26081.524605,25657.025567,25812.415269,25890.292701,-0.005998,1.068064e+10,5.027373e+11
1,BTC,2023-09-03,25869.472793,26087.149165,25817.031798,25969.567353,25919.520073,0.003869,8.962525e+09,5.057740e+11
2,BTC,2023-09-02,25800.909609,25970.284489,25753.093847,25868.798140,25834.853875,0.002631,1.010039e+10,5.037864e+11
3,BTC,2023-09-01,25934.020806,26125.869774,25362.609128,25800.724373,25867.372589,-0.005140,1.720286e+10,5.024359e+11
4,BTC,2023-08-31,27301.929317,27456.079001,25752.929947,25931.472893,26616.701105,-0.050196,2.018100e+10,5.049576e+11

In [6]:
selected_data = data_load.load_selected_data(historical_data, selected_days=1460, end_date="2023-08-01", update=UPDATE_DATA_LOAD)
print(selected_data.shape)
selected_data.head()

(13140, 10)

,symbol,date,open,high,low,close,avg,return,volume,marketcap
0,BTC,2023-08-01,29230.872405,29675.732498,28657.023820,29675.732498,29453.302452,0.015219,1.827239e+10,5.770561e+11
1,BTC,2023-07-31,29278.314054,29489.872869,29131.579034,29230.110879,29254.212467,-0.001646,1.165678e+10,5.683656e+11
2,BTC,2023-07-30,29357.093643,29443.169490,29059.502629,29275.307947,29316.200795,-0.002786,8.678455e+09,5.692170e+11
3,BTC,2023-07-29,29319.446038,29396.843754,29264.166274,29356.918538,29338.182288,0.001278,6.481776e+09,5.707744e+11
4,BTC,2023-07-28,29212.164302,29521.514331,29125.845592,29319.245403,29265.704853,0.003666,1.121847e+10,5.700178e+11

# Clustering Model

In [73]:
# TODO: Add a KPI to measure how much the model worked

In [7]:
return_data = clustering_model.load_return_data(selected_data, update=UPDATE_CLUSTERING_MODEL)
print(return_data.shape)
return_data.head()

return data file saved.
(1460, 9)

,ADA,BNB,BTC,DOGE,ETH,TRX,USDC,USDT,XRP
2019-08-03,0.006022,-0.006930,0.028752,0.001515,0.021087,0.007789,0.001897,0.002819,0.013603
2019-08-04,-0.025946,-0.011713,0.013727,0.008817,0.000399,0.022706,-0.003830,0.000993,0.009404
2019-08-05,0.007287,0.017044,0.077086,0.050633,0.051938,0.030286,0.003959,0.004457,0.012013
2019-08-06,-0.057943,-0.014427,-0.028225,-0.044794,-0.035112,-0.061140,-0.003340,-0.011890,-0.039171
2019-08-07,-0.027501,0.062056,0.040586,0.018657,0.002061,0.000180,0.002045,0.004470,0.001532

In [8]:
clusters_data = clustering_model.load_clusters_data(return_data, UPDATE_CLUSTERING_MODEL)
print(clusters_data['cluster'].unique().shape)
clusters_data.head()

Clusters data file saved.
(3,)

  symbol cluster
0   DOGE       0
1    ADA       1
2    BNB       1
3    BTC       1
4    ETH       1

# Regression Model

In [74]:
# TODO: Add finantioal indexes to regression model
# TODO: Add date (numeric date, year, month, day) to regression model
# TODO: Create a dataframe which has the predicted return and risk for each symbol
# TODO: Add more regression models (LogisticRegression(), SVC(kernel='poly', probability=True), XGBClassifier(), etc)
# TODO: Grid search over parameters

In [9]:
regression_data = regression_model.load_regression_data(selected_data, clusters_data, future_days=30, update=UPDATE_REGRESSION_MODEL)
print(regression_data.shape)
regression_data.head()

(12870, 22)

,future_return,future_risk,open,high,low,close,avg,return,volume,marketcap,...,symbol_BTC,symbol_DOGE,symbol_ETH,symbol_TRX,symbol_USDC,symbol_USDT,symbol_XRP,cluster_0,cluster_1,cluster_2
0,-0.026831,0.021230,0.452811,0.447250,0.455907,0.453192,0.455005,0.005827,0.030012,0.466416,...,True,False,False,False,False,False,False,False,True,False
1,-0.038039,0.021346,0.451102,0.445435,0.456883,0.452738,0.453919,0.020641,0.025890,0.465924,...,True,False,False,False,False,False,False,False,True,False
2,-0.033641,0.021360,0.450651,0.454383,0.445908,0.451068,0.452854,0.006273,0.075184,0.464185,...,True,False,False,False,False,False,False,False,True,False
3,-0.030465,0.022037,0.445393,0.447687,0.452791,0.450596,0.449976,0.063509,0.037556,0.463675,...,True,False,False,False,False,False,False,False,True,False
4,-0.021927,0.023400,0.454429,0.446336,0.450752,0.445281,0.451844,-0.105772,0.041518,0.458185,...,True,False,False,False,False,False,False,False,True,False

In [10]:
# regression_data.plot.scatter(x='close', y='future_return')

In [11]:
from sklearn import linear_model
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [12]:
x = regression_data.loc[:, 'open':]
y = regression_data[['future_return', 'future_risk']]
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = 0.2, random_state = 4)

In [13]:
regr = linear_model.LinearRegression()
regr.fit(train_x, train_y)

train_y_ = regr.predict(train_x)
print(f'Train R2: {(100 * r2_score(train_y, train_y_)):.2f}%')
test_y_ = regr.predict(test_x)
print(f'Test R2: {(100 * r2_score(test_y, test_y_)):.2f}%')

Train R2: 16.36%
Test R2: 16.79%

In [14]:
regr = RandomForestRegressor(n_estimators=100)
regr.fit(train_x, train_y)

train_y_ = regr.predict(train_x)
print(f'Train R2: {(100 * r2_score(train_y, train_y_)):.2f}%')
test_y_ = regr.predict(test_x)
print(f'Test R2: {(100 * r2_score(test_y, test_y_)):.2f}%')

Train R2: 94.31%
Test R2: 58.78%

# Portfolio Selection

In [81]:
# TODO: Add CAPM Model
# TODO: Add Black-Litterman allocation?
# TODO: long and short? weight_bounds=(-1, 1)

In [28]:
close_data = selected_data[["date", "symbol", "close"]]
close_data = close_data.pivot(index="date", columns="symbol")
close_data = close_data["close"]
close_data.columns.name = None
close_data

,ADA,BNB,BTC,DOGE,ETH,TRX,USDC,USDT,XRP
date,,,,,,,,,
2019-08-03,0.057763,27.889860,10821.726510,0.002912,222.490335,0.021929,1.001781,1.004277,0.316757
2019-08-04,0.056271,27.556161,10970.184216,0.002938,222.669727,0.022415,0.998090,1.005068,0.319842
2019-08-05,0.056680,28.011879,11805.653725,0.003087,234.215027,0.023088,1.002105,1.009972,0.323564
2019-08-06,0.053369,27.638088,11478.169346,0.002950,226.020650,0.021669,0.999602,0.998211,0.311326
2019-08-07,0.051906,29.354369,11941.968341,0.003006,226.391008,0.021676,1.001156,1.001961,0.311969
...,...,...,...,...,...,...,...,...,...
2023-07-28,0.310201,241.977042,29319.245403,0.077321,1874.744926,0.085212,1.000166,1.000106,0.712568
2023-07-29,0.312765,242.576364,29356.918538,0.080188,1881.068877,0.083282,1.000058,1.000054,0.712739
2023-07-30,0.315633,242.525986,29275.307947,0.078061,1861.643855,0.080026,1.000022,0.999893,0.705136
2023-07-31,0.307488,241.120656,29230.110879,0.077818,1856.162340,0.077977,1.000010,0.999911,0.698521
2023-08-01,0.309951,247.505020,29675.732498,0.078042,1871.792170,0.078594,1.000072,0.999522,0.707211

In [78]:
# Mean Variance

from pypfopt.expected_returns import mean_historical_return
from pypfopt.risk_models import CovarianceShrinkage
from pypfopt.efficient_frontier import EfficientFrontier

m = mean_historical_return(close_data)  # mu = expected_returns.mean_historical_return(df)
s = CovarianceShrinkage(close_data).ledoit_wolf()  # S = risk_models.sample_cov(df)
ef = EfficientFrontier(m, s)
weights = ef.max_sharpe()
cleaned_weights = ef.clean_weights()

ef.portfolio_performance(verbose=True)
print(dict(cleaned_weights))

Expected annual return: 51.3%
Annual volatility: 70.3%
Sharpe Ratio: 0.70
{'ADA': 0.01202, 'BNB': 0.37846, 'BTC': 0.0, 'DOGE': 0.2007, 'ETH': 0.40882, 'TRX': 0.0, 'USDC': 0.0, 'USDT': 0.0, 'XRP': 0.0}

In [69]:
# Hierarchical Risk Parity

from pypfopt import HRPOpt

returns = close_data.pct_change().dropna()
hrp = HRPOpt(returns)
weights = hrp.optimize()
cleaned_weights = hrp.clean_weights()

hrp.portfolio_performance(verbose=True)
print(dict(cleaned_weights))

Expected annual return: 0.6%
Annual volatility: 4.6%
Sharpe Ratio: -0.31
{'ADA': 0.00105, 'BNB': 0.00114, 'BTC': 0.00136, 'DOGE': 0.00052, 'ETH': 0.0008, 'TRX': 0.00126, 'USDC': 0.47947, 'USDT': 0.51242, 'XRP': 0.00198}

In [72]:
# mCVAR

from pypfopt.efficient_frontier import EfficientCVaR

m = mean_historical_return(close_data)
s = close_data.cov()
ef_cvar = EfficientCVaR(m, s)
cvar_weights = ef_cvar.min_cvar()
cleaned_weights = ef_cvar.clean_weights()

ef_cvar.portfolio_performance(verbose=True)
print(dict(cleaned_weights))

Expected annual return: -0.0%
Conditional Value at Risk: -0.00%
{'ADA': 0.0, 'BNB': 0.0, 'BTC': 0.0, 'DOGE': 0.0, 'ETH': 0.0, 'TRX': 0.0, 'USDC': 0.20652, 'USDT': 0.78967, 'XRP': 0.0038}