# Import Modules and Config

In [1]:
import data_load
import clustering_model
import regression_model
%load_ext autoreload
%autoreload 2

In [2]:
UPDATE_DATA_LOAD = False
UPDATE_CLUSTERING_MODEL = True
UPDATE_REGRESSION_MODEL = True

# Data Load

In [3]:
basic_data = data_load.load_basic_data(
    selected_symbols=10, 
    max_date_added_year=2020, 
    min_last_update_year=2023, 
    min_market_pairs=6, 
    update=UPDATE_DATA_LOAD
)
print(basic_data.shape)
basic_data.head()

(10, 19)

,id,name,symbol,slug,tags,cmcRank,marketPairCount,circulatingSupply,selfReportedCirculatingSupply,totalSupply,maxSupply,isActive,lastUpdated,dateAdded,quotes,isAudited,badges,auditInfoList,platform
0,1,Bitcoin,BTC,bitcoin,"['mineable', 'pow', 'sha-256', 'store-of-value...",1,10493,1.951237e+07,0,1.951237e+07,2.100000e+07,1,2023-10-13T09:04:00.000Z,2010-07-13T00:00:00.000Z,"[{'name': 'USD', 'price': 26800.522640046795, ...",False,[1],NaN,NaN
1,1027,Ethereum,ETH,ethereum,"['pos', 'smart-contracts', 'ethereum-ecosystem...",2,7546,1.202549e+08,0,1.202549e+08,NaN,1,2023-10-13T09:04:00.000Z,2015-08-07T00:00:00.000Z,"[{'name': 'USD', 'price': 1548.4278234952615, ...",False,"[1, 4]",[],NaN
2,825,Tether USDt,USDT,tether,"['payments', 'stablecoin', 'asset-backed-stabl...",3,63642,8.352203e+10,0,8.662567e+10,NaN,1,2023-10-13T09:04:00.000Z,2015-02-25T00:00:00.000Z,"[{'name': 'USD', 'price': 0.999723105320604, '...",True,[],"[{'coinId': '825', 'auditor': 'CertiK', 'audit...","{'id': 1, 'name': 'Ethereum', 'symbol': 'ETH',..."
3,1839,BNB,BNB,bnb,"['marketplace', 'centralized-exchange', 'payme...",4,1679,1.538451e+08,0,1.538451e+08,NaN,1,2023-10-13T09:04:00.000Z,2017-07-25T00:00:00.000Z,"[{'name': 'USD', 'price': 205.77786499801198, ...",True,"[1, 3]","[{'coinId': '1839', 'auditor': 'CertiK', 'audi...",NaN
4,52,XRP,XRP,xrp,"['medium-of-exchange', 'enterprise-solutions',...",5,1113,5.344103e+10,0,9.998836e+10,1.000000e+11,1,2023-10-13T09:04:00.000Z,2013-08-04T00:00:00.000Z,"[{'name': 'USD', 'price': 0.4819245630066666, ...",True,"[1, 3]","[{'coinId': '52', 'auditor': 'CertiK', 'auditS...",NaN

In [4]:
symbols_list = basic_data["symbol"].to_list()
historical_data = data_load.load_historical_data(
    symbols_list,
    update=UPDATE_DATA_LOAD
)
print(historical_data.shape)
historical_data.head()

(26597, 10)

,symbol,date,open,high,low,close,avg,return,volume,marketcap
0,BTC,2023-10-12,26873.292491,26921.438903,26558.320784,26756.798639,26815.045565,-0.004335,9.392909e+09,5.220780e+11
1,BTC,2023-10-11,27392.075546,27474.116187,26561.099366,26873.321121,27132.698333,-0.018938,1.364809e+10,5.243250e+11
2,BTC,2023-10-10,27589.201102,27715.848347,27301.655078,27391.019517,27490.110310,-0.007183,9.973351e+09,5.343984e+11
3,BTC,2023-10-09,27934.472162,27989.470902,27302.561919,27583.678595,27759.075379,-0.012558,1.200767e+10,5.381279e+11
4,BTC,2023-10-08,27971.678107,28102.170391,27740.663024,27935.089581,27953.383844,-0.001308,7.916875e+09,5.449575e+11

In [5]:
selected_data = data_load.load_selected_data(
    historical_data, 
    selected_days=1460, 
    end_date="2023-10-10", 
    update=UPDATE_DATA_LOAD
)
print(selected_data.shape)
selected_data.head()

(13140, 10)

,symbol,date,open,high,low,close,avg,return,volume,marketcap
0,BTC,2023-10-10,27589.201102,27715.848347,27301.655078,27391.019517,27490.110310,-0.007183,9.973351e+09,5.343984e+11
1,BTC,2023-10-09,27934.472162,27989.470902,27302.561919,27583.678595,27759.075379,-0.012558,1.200767e+10,5.381279e+11
2,BTC,2023-10-08,27971.678107,28102.170391,27740.663024,27935.089581,27953.383844,-0.001308,7.916875e+09,5.449575e+11
3,BTC,2023-10-07,27946.781633,28028.092087,27870.423458,27968.838871,27957.810252,0.000789,6.553044e+09,5.455899e+11
4,BTC,2023-10-06,27412.122424,28252.537570,27215.552446,27946.596780,27679.359602,0.019498,1.349239e+10,5.451267e+11

# Clustering Model

In [9]:
# TODO: Add a KPI to measure how much the model worked

In [6]:
return_data = clustering_model.load_return_data(
    selected_data, 
    update=UPDATE_CLUSTERING_MODEL
)
print(return_data.shape)
return_data.head()

return data file saved.
(1460, 9)

,ADA,BNB,BTC,DOGE,ETH,TRX,USDC,USDT,XRP
2019-10-12,0.000053,0.033728,0.002512,0.005015,-0.009354,-0.016072,-0.004148,-0.007881,0.007657
2019-10-13,0.019357,0.060925,-0.001907,0.046538,0.006711,0.025739,0.000226,0.000532,0.016974
2019-10-14,0.011243,0.008273,0.006472,0.039529,0.027097,0.036808,-0.000418,-0.000642,0.068065
2019-10-15,-0.048566,0.006446,-0.020074,-0.014151,-0.029795,-0.058775,0.001337,-0.000194,-0.026097
2019-10-16,-0.025635,-0.036556,-0.019153,0.039411,-0.029393,-0.028902,0.000364,0.002089,-0.014730

In [7]:
clusters_data = clustering_model.load_clusters_data(
    return_data, 
    UPDATE_CLUSTERING_MODEL
)
print(clusters_data['cluster'].unique().shape)
clusters_data.head()

Clusters data file saved.
(3,)

  symbol cluster
0   DOGE       0
1    ADA       1
2    BNB       1
3    BTC       1
4    ETH       1

# Regression Model

In [12]:
# TODO: Use ANN models
# TODO: Add financial indexes to regression model
# TODO: Create a dataframe which has the predicted return and risk for each symbol
# TODO: Add more regression models (LogisticRegression(), SVC(kernel='poly', probability=True), XGBClassifier(), etc)
# TODO: Grid search over parameters

In [19]:
regression_data = regression_model.load_regression_data(
    selected_data, 
    clusters_data, 
    future_days=30, 
    update=UPDATE_REGRESSION_MODEL
)
print(regression_data.shape)
regression_data.head()

(12870, 27)

,future_return,future_risk,open,high,low,close,avg,return,volume,marketcap,...,symbol_BTC,symbol_DOGE,symbol_ETH,symbol_TRX,symbol_USDC,symbol_USDT,symbol_XRP,cluster_0,cluster_1,cluster_2
0,0.051702,0.024500,0.383350,0.377646,0.386253,0.382321,0.384529,-0.012939,0.022508,0.394765,...,True,False,False,False,False,False,False,False,True,False
1,0.055933,0.023589,0.383501,0.376830,0.388817,0.383260,0.385077,-0.002002,0.015618,0.395715,...,True,False,False,False,False,False,False,False,True,False
2,0.066892,0.024524,0.388532,0.383982,0.386814,0.383408,0.387677,-0.068828,0.030821,0.395849,...,True,False,False,False,False,False,False,False,True,False
3,0.056419,0.025652,0.381176,0.383914,0.385770,0.388359,0.386470,0.101629,0.031594,0.400943,...,True,False,False,False,False,False,False,False,True,False
4,0.072685,0.024508,0.381703,0.377281,0.382699,0.381152,0.383115,-0.006333,0.036336,0.393485,...,True,False,False,False,False,False,False,False,True,False

In [15]:
# regression_data.plot.scatter(x='close', y='future_return')

In [22]:
from sklearn import linear_model
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [23]:
x = regression_data.loc[:, 'open':]
y = regression_data[['future_return', 'future_risk']]
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = 0.2, random_state = 4)

In [24]:
regr = linear_model.LinearRegression()
regr.fit(train_x, train_y)

train_y_ = regr.predict(train_x)
print(f'Train R2: {(100 * r2_score(train_y, train_y_)):.2f}%')
test_y_ = regr.predict(test_x)
print(f'Test R2: {(100 * r2_score(test_y, test_y_)):.2f}%')

Train R2: 20.26%
Test R2: 20.55%

In [25]:
regr = RandomForestRegressor(n_estimators=100)
regr.fit(train_x, train_y)

train_y_ = regr.predict(train_x)
print(f'Train R2: {(100 * r2_score(train_y, train_y_)):.2f}%')
test_y_ = regr.predict(test_x)
print(f'Test R2: {(100 * r2_score(test_y, test_y_)):.2f}%')

Train R2: 97.77%
Test R2: 85.01%

# Portfolio Selection

In [81]:
# TODO: Use clustering models
# TODO: Add CAPM Model
# TODO: Add Black-Litterman allocation?
# TODO: long and short? weight_bounds=(-1, 1)

In [28]:
close_data = selected_data[["date", "symbol", "close"]]
close_data = close_data.pivot(index="date", columns="symbol")
close_data = close_data["close"]
close_data.columns.name = None
close_data

,ADA,BNB,BTC,DOGE,ETH,TRX,USDC,USDT,XRP
date,,,,,,,,,
2019-08-03,0.057763,27.889860,10821.726510,0.002912,222.490335,0.021929,1.001781,1.004277,0.316757
2019-08-04,0.056271,27.556161,10970.184216,0.002938,222.669727,0.022415,0.998090,1.005068,0.319842
2019-08-05,0.056680,28.011879,11805.653725,0.003087,234.215027,0.023088,1.002105,1.009972,0.323564
2019-08-06,0.053369,27.638088,11478.169346,0.002950,226.020650,0.021669,0.999602,0.998211,0.311326
2019-08-07,0.051906,29.354369,11941.968341,0.003006,226.391008,0.021676,1.001156,1.001961,0.311969
...,...,...,...,...,...,...,...,...,...
2023-07-28,0.310201,241.977042,29319.245403,0.077321,1874.744926,0.085212,1.000166,1.000106,0.712568
2023-07-29,0.312765,242.576364,29356.918538,0.080188,1881.068877,0.083282,1.000058,1.000054,0.712739
2023-07-30,0.315633,242.525986,29275.307947,0.078061,1861.643855,0.080026,1.000022,0.999893,0.705136
2023-07-31,0.307488,241.120656,29230.110879,0.077818,1856.162340,0.077977,1.000010,0.999911,0.698521
2023-08-01,0.309951,247.505020,29675.732498,0.078042,1871.792170,0.078594,1.000072,0.999522,0.707211

In [78]:
# Mean Variance

from pypfopt.expected_returns import mean_historical_return
from pypfopt.risk_models import CovarianceShrinkage
from pypfopt.efficient_frontier import EfficientFrontier

m = mean_historical_return(close_data)  # mu = expected_returns.mean_historical_return(df)
s = CovarianceShrinkage(close_data).ledoit_wolf()  # S = risk_models.sample_cov(df)
ef = EfficientFrontier(m, s)
weights = ef.max_sharpe()
cleaned_weights = ef.clean_weights()

ef.portfolio_performance(verbose=True)
print(dict(cleaned_weights))

Expected annual return: 51.3%
Annual volatility: 70.3%
Sharpe Ratio: 0.70
{'ADA': 0.01202, 'BNB': 0.37846, 'BTC': 0.0, 'DOGE': 0.2007, 'ETH': 0.40882, 'TRX': 0.0, 'USDC': 0.0, 'USDT': 0.0, 'XRP': 0.0}

In [69]:
# Hierarchical Risk Parity

from pypfopt import HRPOpt

returns = close_data.pct_change().dropna()
hrp = HRPOpt(returns)
weights = hrp.optimize()
cleaned_weights = hrp.clean_weights()

hrp.portfolio_performance(verbose=True)
print(dict(cleaned_weights))

Expected annual return: 0.6%
Annual volatility: 4.6%
Sharpe Ratio: -0.31
{'ADA': 0.00105, 'BNB': 0.00114, 'BTC': 0.00136, 'DOGE': 0.00052, 'ETH': 0.0008, 'TRX': 0.00126, 'USDC': 0.47947, 'USDT': 0.51242, 'XRP': 0.00198}

In [72]:
# mCVAR

from pypfopt.efficient_frontier import EfficientCVaR

m = mean_historical_return(close_data)
s = close_data.cov()
ef_cvar = EfficientCVaR(m, s)
cvar_weights = ef_cvar.min_cvar()
cleaned_weights = ef_cvar.clean_weights()

ef_cvar.portfolio_performance(verbose=True)
print(dict(cleaned_weights))

Expected annual return: -0.0%
Conditional Value at Risk: -0.00%
{'ADA': 0.0, 'BNB': 0.0, 'BTC': 0.0, 'DOGE': 0.0, 'ETH': 0.0, 'TRX': 0.0, 'USDC': 0.20652, 'USDT': 0.78967, 'XRP': 0.0038}