In [1]:
# https://www.relataly.com/crypto-market-cluster-analysis-using-affinity-propagation-python/8114/

In [2]:
# reload modules
%load_ext autoreload
%autoreload 2

In [3]:
import data_load
import clustering_model

# Data Load

In [4]:
basic_data = data_load.load_basic_data()
print(basic_data.shape)
basic_data.head()

(320, 18)

,id,name,symbol,slug,tags,cmcRank,marketPairCount,circulatingSupply,selfReportedCirculatingSupply,totalSupply,maxSupply,isActive,lastUpdated,dateAdded,quotes,isAudited,auditInfoList,platform
0,1,Bitcoin,BTC,bitcoin,"['mineable', 'pow', 'sha-256', 'store-of-value...",1,10278,1.942026e+07,0.0,1.942026e+07,2.100000e+07,1,2023-07-05T05:01:00.000Z,2010-07-13T00:00:00.000Z,"[{'name': 'USD', 'price': 30837.28822501044, '...",False,NaN,NaN
1,1027,Ethereum,ETH,ethereum,"['pos', 'smart-contracts', 'ethereum-ecosystem...",2,7068,1.202176e+08,0.0,1.202176e+08,NaN,1,2023-07-05T05:01:00.000Z,2015-08-07T00:00:00.000Z,"[{'name': 'USD', 'price': 1937.196498176435, '...",False,[],NaN
2,1839,BNB,BNB,bnb,"['marketplace', 'centralized-exchange', 'payme...",4,1475,1.558506e+08,0.0,1.558506e+08,NaN,1,2023-07-05T05:01:00.000Z,2017-07-25T00:00:00.000Z,"[{'name': 'USD', 'price': 243.528037849361, 'v...",True,"[{'coinId': '1839', 'auditor': 'CertiK', 'audi...",NaN
3,52,XRP,XRP,xrp,"['medium-of-exchange', 'enterprise-solutions',...",6,972,5.225429e+10,0.0,9.998866e+10,1.000000e+11,1,2023-07-05T05:01:00.000Z,2013-08-04T00:00:00.000Z,"[{'name': 'USD', 'price': 0.49092645510058036,...",True,"[{'coinId': '52', 'auditor': 'CertiK', 'auditS...",NaN
4,2010,Cardano,ADA,cardano,"['dpos', 'pos', 'platform', 'research', 'smart...",7,850,3.495589e+10,0.0,3.595238e+10,4.500000e+10,1,2023-07-05T05:01:00.000Z,2017-10-01T00:00:00.000Z,"[{'name': 'USD', 'price': 0.29356399231299274,...",False,NaN,NaN

In [5]:
historical_data = data_load.load_historical_data(basic_data)
print(historical_data.shape)
historical_data.head()

(499123, 10)

,symbol,date,open,high,low,close,avg,return,volume,marketcap
0,BTC,2023-07-04,31156.864922,31325.198166,30659.355893,30777.581511,30967.223216,-0.012173,1.281083e+10,5.977022e+11
1,BTC,2023-07-03,30624.516311,31375.613252,30586.513433,31156.439492,30890.477901,0.017369,1.527188e+10,6.050312e+11
2,BTC,2023-07-02,30587.269956,30766.139747,30264.018714,30620.770263,30604.020110,0.001095,1.053342e+10,5.946020e+11
3,BTC,2023-07-01,30471.847563,30641.289323,30328.864749,30590.079072,30530.963317,0.003880,9.086607e+09,5.939744e+11
4,BTC,2023-06-30,30441.353759,31256.862700,29600.275939,30477.251282,30459.302521,0.001179,2.638731e+10,5.917583e+11

# Clustering Model

In [6]:
return_data = clustering_model.load_return_data(historical_data)
print(return_data.shape)
return_data.head()

(730, 305)

,1INCH,AAVE,ABBC,ACH,ADA,ADS,AERGO,AGIX,AKT,ALGO,...,XVS,XYO,YFI,YFII,ZEC,ZEN,ZIL,ZRX,ankrETH,stETH
0,-0.018895,0.110853,-0.035474,0.008349,-0.038545,0.033898,-0.001828,0.046165,0.053214,-0.006942,...,-0.014598,-0.039070,-0.027204,0.032655,-0.073451,-0.061713,-0.038892,-0.040905,-0.046202,-0.050650
1,0.139607,0.028900,-0.027834,0.052004,0.009497,0.068308,0.028235,0.060823,-0.076748,0.045610,...,0.056719,0.031629,0.108903,0.013975,0.055164,0.071251,0.011328,0.026541,0.051585,0.057460
2,-0.027239,-0.007797,-0.033193,0.000846,-0.009204,0.015144,-0.021960,0.035163,-0.018598,-0.008445,...,-0.027023,0.005628,-0.016337,-0.045094,0.004969,-0.050212,0.004417,0.104815,-0.001737,-0.007142
3,-0.090956,-0.072816,-0.043090,-0.137035,-0.053252,-0.013459,-0.087418,-0.081541,-0.096779,-0.041261,...,-0.098932,-0.065893,-0.065557,-0.026339,-0.076633,-0.070618,-0.078269,0.044194,-0.090706,-0.079457
4,0.027571,0.043622,0.060045,0.021621,0.016731,0.086890,0.024770,0.159592,0.032592,0.044245,...,0.023543,0.013857,0.013423,0.029807,0.016537,0.017902,0.001747,0.006463,0.016393,0.010827

In [7]:
clusters_data = clustering_model.load_clusters_data(return_data)
print(clusters_data['cluster'].unique().shape)
clusters_data.head()

(95,)

  symbol  cluster
0   ABBC        0
1    ACH        1
2   AMPL        2
3    AOG        3
4    BFC        3

# Regression Model

In [8]:
import numpy as np
from sklearn import linear_model
from sklearn.metrics import r2_score

In [9]:
days = 30  #TODO: add to config

In [10]:
regression_data = historical_data.merge(
    clusters_data,
    on='symbol',
    how='inner'
)

regression_data

,symbol,date,open,high,low,close,avg,return,volume,marketcap,cluster
0,BTC,2023-07-04,31156.864922,31325.198166,30659.355893,30777.581511,30967.223216,-0.012173,1.281083e+10,5.977022e+11,89
1,BTC,2023-07-03,30624.516311,31375.613252,30586.513433,31156.439492,30890.477901,0.017369,1.527188e+10,6.050312e+11,89
2,BTC,2023-07-02,30587.269956,30766.139747,30264.018714,30620.770263,30604.020110,0.001095,1.053342e+10,5.946020e+11,89
3,BTC,2023-07-01,30471.847563,30641.289323,30328.864749,30590.079072,30530.963317,0.003880,9.086607e+09,5.939744e+11,89
4,BTC,2023-06-30,30441.353759,31256.862700,29600.275939,30477.251282,30459.302521,0.001179,2.638731e+10,5.917583e+11,89
...,...,...,...,...,...,...,...,...,...,...,...
489804,SRM,2020-08-15,1.858135,1.893875,1.653225,1.664159,1.761147,-0.104393,4.380330e+07,8.320793e+07,29
489805,SRM,2020-08-14,2.029597,2.164305,1.821478,1.861319,1.945458,-0.082912,6.367864e+07,9.306594e+07,29
489806,SRM,2020-08-13,1.682308,2.221409,1.639467,2.029851,1.856079,0.206587,1.492122e+08,0.000000e+00,29
489807,SRM,2020-08-12,1.555740,1.982487,1.555740,1.690087,1.622914,0.086356,2.625532e+08,0.000000e+00,29
489808,SRM,2020-08-11,0.110091,1.607618,0.110006,1.570353,0.840222,13.264118,2.112328e+08,0.000000e+00,29

In [11]:
regression_data['future_return'] = ((1 + regression_data['return']).rolling(window=days).apply(np.prod, raw=True) - 1).shift(1)
regression_data['future_risk'] = regression_data['return'].rolling(window=days).agg(np.var)
regression_data.loc[regression_data.groupby('symbol').cumcount() < days, ['future_return', 'future_risk']] = np.nan
regression_data.dropna(inplace=True)  # subset='future_return'

regression_data

,symbol,date,open,high,low,close,avg,return,volume,marketcap,cluster,future_return,future_risk
30,BTC,2023-06-04,27075.122073,27407.018570,26968.224141,27119.067193,27097.094633,0.001623,9.360912e+09,5.259202e+11,89,0.138635,0.000623
31,BTC,2023-06-03,27252.323333,27317.051854,26958.003740,27075.129398,27163.726366,-0.006502,8.385597e+09,5.250436e+11,89,0.154538,0.000621
32,BTC,2023-06-02,26824.556981,27303.861687,26574.644421,27249.588949,27037.072965,0.015845,1.483741e+10,5.284044e+11,89,0.127448,0.000625
33,BTC,2023-06-01,27218.412376,27346.105483,26671.721156,26819.973220,27019.192798,-0.014639,1.467897e+10,5.200450e+11,89,0.144059,0.000638
34,BTC,2023-05-31,27700.530089,27831.677804,26866.453944,27219.658608,27460.094348,-0.017360,1.565637e+10,5.277732e+11,89,0.122955,0.000653
...,...,...,...,...,...,...,...,...,...,...,...,...,...
489804,SRM,2020-08-15,1.858135,1.893875,1.653225,1.664159,1.761147,-0.104393,4.380330e+07,8.320793e+07,29,0.468858,0.015578
489805,SRM,2020-08-14,2.029597,2.164305,1.821478,1.861319,1.945458,-0.082912,6.367864e+07,9.306594e+07,29,0.293591,0.015881
489806,SRM,2020-08-13,1.682308,2.221409,1.639467,2.029851,1.856079,0.206587,1.492122e+08,0.000000e+00,29,0.201487,0.017118
489807,SRM,2020-08-12,1.555740,1.982487,1.555740,1.690087,1.622914,0.086356,2.625532e+08,0.000000e+00,29,0.438105,0.017256
489808,SRM,2020-08-11,0.110091,1.607618,0.110006,1.570353,0.840222,13.264118,2.112328e+08,0.000000e+00,29,0.507497,5.859428

In [14]:
regr = linear_model.LinearRegression()
x = regression_data[['return', 'volume', 'marketcap']]
y = regression_data[['future_return', 'future_risk']]

regr.fit(x, y)
y_ = regr.predict(x)

print(f'MAE: {abs(y_ - y).mean()[0]} \nMSE: {((y_ - y) ** 2).mean()[0]} \nRSQ: {r2_score(y, y_)}')

MAE: 3.6061809044402633
MSE: 22435.711457940644
RSQ: 0.01334223755445696