In [5]:
# https://www.relataly.com/crypto-market-cluster-analysis-using-affinity-propagation-python/8114/

In [6]:
# reload modules
%load_ext autoreload
%autoreload 2

In [7]:
import data_load
import clustering_model

# Data Load

In [8]:
basic_data = data_load.load_basic_data()
print(basic_data.shape)
basic_data.head()

Fetching basic data...

OSError: Cannot save file into a non-existent directory: 'data'

In [6]:
historical_data = data_load.load_historical_data(basic_data)
print(historical_data.shape)
historical_data.head()

(495527, 10)

,symbol,date,open,high,low,close,avg,return,volume,marketcap
0,BTC,2023-06-29,30086.186717,30796.250240,30057.203020,30445.351226,30265.768972,0.011938,1.318086e+10,5.911079e+11
1,BTC,2023-06-28,30696.561487,30703.279976,29921.822833,30086.246189,30391.403838,-0.019882,1.457150e+10,5.841087e+11
2,BTC,2023-06-27,30274.321188,31006.786577,30236.651294,30688.163854,30481.242521,0.013670,1.642883e+10,5.957737e+11
3,BTC,2023-06-26,30480.523973,30636.029430,29955.743294,30271.131017,30375.827495,-0.006870,1.649319e+10,5.876504e+11
4,BTC,2023-06-25,30545.150233,31041.272067,30327.942784,30480.261606,30512.705920,-0.002124,1.270346e+10,5.916836e+11

# Clustering Model

In [7]:
return_data = clustering_model.load_return_data(historical_data)
print(return_data.shape)
return_data.head()

(730, 303)

,1INCH,AAVE,ABBC,ACH,ADA,ADS,AERGO,AGIX,AKT,ALGO,...,XVS,XYO,YFI,YFII,ZEC,ZEN,ZIL,ZRX,ankrETH,stETH
0,-0.004131,0.051514,-0.039845,0.007483,0.007650,0.024788,0.122452,0.025720,-0.076627,-0.006805,...,-0.016324,0.016465,0.005219,0.036302,0.036524,0.019644,0.019976,0.017863,0.044062,0.048406
1,-0.061561,-0.076120,0.083215,-0.052109,-0.034833,-0.002708,0.300415,-0.022499,-0.063816,-0.049691,...,-0.067624,-0.044017,-0.051706,-0.021036,-0.077117,-0.085665,-0.065033,-0.067079,-0.067861,-0.072347
2,0.009549,0.013579,-0.040492,0.071689,0.046105,0.034380,-0.157211,0.005380,0.014673,0.013543,...,-0.015801,0.001921,0.001615,-0.001258,-0.013510,0.004059,-0.008116,0.003793,0.011079,0.013412
3,0.031052,0.108650,-0.013303,-0.027704,0.009098,0.011219,0.070054,0.113821,0.001438,0.035646,...,0.077748,0.028174,0.018877,0.042064,-0.019410,0.067618,0.009340,0.016838,0.038868,0.040611
4,0.020046,0.068001,0.003385,0.012540,0.038587,0.052541,0.037633,0.047662,0.022809,0.003291,...,0.078850,0.028030,0.023124,0.088637,0.034042,0.010879,0.008263,0.029860,0.042709,0.043635

In [8]:
clusters_data = clustering_model.load_clusters_data(return_data)
print(clusters_data['cluster'].unique().shape)
clusters_data.head()

(96,)

  symbol  cluster
0   ABBC        0
1    ACH        1
2   AGIX        2
3    FET        2
4   AMPL        3

In [9]:
regression_data = historical_data.merge(
    clusters_data,
    on='symbol',
    how='inner'
)

regression_data

,symbol,date,open,high,low,close,avg,return,volume,marketcap,cluster
0,BTC,2023-06-29,30086.186717,30796.250240,30057.203020,30445.351226,30265.768972,0.011938,1.318086e+10,5.911079e+11,90
1,BTC,2023-06-28,30696.561487,30703.279976,29921.822833,30086.246189,30391.403838,-0.019882,1.457150e+10,5.841087e+11,90
2,BTC,2023-06-27,30274.321188,31006.786577,30236.651294,30688.163854,30481.242521,0.013670,1.642883e+10,5.957737e+11,90
3,BTC,2023-06-26,30480.523973,30636.029430,29955.743294,30271.131017,30375.827495,-0.006870,1.649319e+10,5.876504e+11,90
4,BTC,2023-06-25,30545.150233,31041.272067,30327.942784,30480.261606,30512.705920,-0.002124,1.270346e+10,5.916836e+11,90
...,...,...,...,...,...,...,...,...,...,...,...
486283,TVK,2020-12-20,0.056961,0.058968,0.050973,0.055196,0.056079,-0.030989,5.836950e+05,0.000000e+00,80
486284,TVK,2020-12-19,0.054730,0.061696,0.053188,0.056962,0.055846,0.040766,6.570442e+05,0.000000e+00,80
486285,TVK,2020-12-18,0.057150,0.059837,0.053772,0.054732,0.055941,-0.042309,5.495110e+05,0.000000e+00,80
486286,TVK,2020-12-17,0.066999,0.067000,0.054606,0.057151,0.062075,-0.146982,8.008711e+05,0.000000e+00,80
486287,TVK,2020-12-16,0.060753,0.067037,0.060752,0.066994,0.063874,0.102725,1.342265e+06,0.000000e+00,80