In [1]:
from src import data_preparation as dp
from src import model_calculation as mc
%load_ext autoreload
%autoreload 2

In [2]:
DATE = "2023-10-01"
FUTURE_DAYS = 60
SYMBOLS = 20

# Data Load

In [3]:
basic_df = dp.load_basic_data(
    selected_symbols=SYMBOLS, 
    max_date_added_year=2020, 
    min_last_update_year=2023, 
    min_market_pairs=6, 
    update=False
)
print(basic_df.shape)
basic_df.head()

Fetching basic data...
Basic data file saved.
(19, 19)

,id,name,symbol,slug,tags,cmcRank,marketPairCount,circulatingSupply,selfReportedCirculatingSupply,totalSupply,maxSupply,isActive,lastUpdated,dateAdded,quotes,isAudited,badges,auditInfoList,platform
0,1,Bitcoin,BTC,bitcoin,"[mineable, pow, sha-256, store-of-value, state...",1,10649,1.957044e+07,0,1.957044e+07,2.100000e+07,1,2023-12-15T09:17:00.000Z,2010-07-13T00:00:00.000Z,"[{'name': 'USD', 'price': 42984.99337290091, '...",False,[1],NaN,NaN
1,1027,Ethereum,ETH,ethereum,"[pos, smart-contracts, ethereum-ecosystem, coi...",2,8049,1.202066e+08,0,1.202066e+08,NaN,1,2023-12-15T09:17:00.000Z,2015-08-07T00:00:00.000Z,"[{'name': 'USD', 'price': 2284.685453789996, '...",False,[],[],NaN
2,825,Tether USDt,USDT,tether,"[payments, stablecoin, asset-backed-stablecoin...",3,68235,9.081794e+10,0,9.360908e+10,NaN,1,2023-12-15T09:16:00.000Z,2015-02-25T00:00:00.000Z,"[{'name': 'USD', 'price': 1.0002677153961643, ...",True,[],"[{'coinId': '825', 'auditor': 'CertiK', 'audit...","{'id': 1, 'name': 'Ethereum', 'symbol': 'ETH',..."
3,1839,BNB,BNB,bnb,"[marketplace, centralized-exchange, payments, ...",4,1847,1.516959e+08,0,1.516959e+08,NaN,1,2023-12-15T09:16:00.000Z,2017-07-25T00:00:00.000Z,"[{'name': 'USD', 'price': 250.77726021615257, ...",True,[],"[{'coinId': '1839', 'auditor': 'CertiK', 'audi...",NaN
4,52,XRP,XRP,xrp,"[medium-of-exchange, enterprise-solutions, arr...",5,1174,5.400560e+10,0,9.998815e+10,1.000000e+11,1,2023-12-15T09:17:00.000Z,2013-08-04T00:00:00.000Z,"[{'name': 'USD', 'price': 0.634284932679037, '...",True,[3],"[{'coinId': '52', 'auditor': 'CertiK', 'auditS...",NaN

In [4]:
symbols_list = basic_df["symbol"].to_list()
historical_df = dp.load_historical_data(
    symbols_list,
    update=False
)
print(historical_df.shape)
historical_df.head()

1/19 Historical data for BTC successfully fetched.
2/19 Historical data for ETH successfully fetched.
3/19 Historical data for USDT successfully fetched.
4/19 Historical data for BNB successfully fetched.
5/19 Historical data for XRP successfully fetched.
6/19 Historical data for SOL successfully fetched.
7/19 Historical data for USDC successfully fetched.
8/19 Historical data for ADA successfully fetched.
9/19 Historical data for AVAX successfully fetched.
10/19 Historical data for DOGE successfully fetched.
11/19 Historical data for DOT successfully fetched.
12/19 Historical data for TRX successfully fetched.
13/19 Historical data for LINK successfully fetched.
14/19 Historical data for MATIC successfully fetched.
15/19 Historical data for SHIB successfully fetched.
16/19 Historical data for DAI successfully fetched.
17/19 Historical data for LTC successfully fetched.
18/19 Historical data for BCH successfully fetched.
19/19 Historical data for ATOM successfully fetched.
Historical data file saved.
(43592, 10)

,symbol,date,open,high,low,close,avg,return,volume,marketcap
0,BTC,2023-12-14,42884.262692,43390.860374,41767.090540,43023.971974,42954.117333,0.003258,2.557853e+10,8.419834e+11
1,BTC,2023-12-13,41468.465862,43429.780621,40676.868161,42890.740734,42179.603298,0.034298,2.679788e+10,8.393337e+11
2,BTC,2023-12-12,41238.733390,42048.303782,40667.561851,41450.222190,41344.477790,0.005128,2.477952e+10,8.111067e+11
3,BTC,2023-12-11,43792.017858,43808.373056,40234.578335,41243.833315,42517.925586,-0.058188,4.063267e+10,8.070286e+11
4,BTC,2023-12-10,43728.383480,44034.624969,43593.283795,43779.697288,43754.040384,0.001173,1.300048e+10,8.566080e+11

In [5]:
filtered_df = dp.load_filtered_data(
    historical_df, 
    selected_days=1460, 
    end_date=DATE
)
print(filtered_df.shape)
filtered_df.head()

delete symbols which do not have at least 1460 days of return data: ['AVAX', 'DAI', 'DOT', 'SHIB', 'SOL']
delete symbols which do not have the last day of return data: []
delete symbols which do not have the first day of return data: ['LINK']
(18980, 10)

,symbol,date,open,high,low,close,avg,return,volume,marketcap
0,BTC,2023-10-01,26967.397433,28047.237710,26965.094292,27983.750382,27475.573907,0.037688,9.503917e+09,5.457193e+11
1,BTC,2023-09-30,26911.689185,27091.795508,26888.967804,26967.916301,26939.802743,0.002089,5.331173e+09,5.258856e+11
2,BTC,2023-09-29,27024.841714,27225.938430,26721.762797,26911.721603,26968.281658,-0.004186,1.039644e+10,5.247665e+11
3,BTC,2023-09-28,26355.812395,27259.499223,26327.321712,27021.546765,26688.679580,0.025259,1.407900e+10,5.268837e+11
4,BTC,2023-09-27,26209.498349,26817.842315,26111.464382,26352.717619,26281.107984,0.005464,1.171838e+10,5.138185e+11

# Clustering Model

In [6]:
return_df = dp.load_return_data(filtered_df)
print(return_df.shape)
return_df.head()

(1460, 13)

,ADA,ATOM,BCH,BNB,BTC,DOGE,ETH,LTC,MATIC,TRX,USDC,USDT,XRP
2019-10-03,-0.026350,-0.009270,-0.014108,-0.013793,-0.015586,-0.010227,-0.030461,0.000213,-0.016274,-0.007453,0.001515,0.000723,-0.022081
2019-10-04,0.034009,0.002692,0.002633,0.001932,-0.006484,0.015718,0.009967,0.005829,0.004679,0.024989,0.003108,0.004106,0.024246
2019-10-05,0.001881,0.062091,0.000178,-0.001673,-0.007143,-0.013858,-0.003361,0.000604,-0.011685,0.027481,-0.006509,-0.006154,-0.000597
2019-10-06,-0.009788,-0.030181,0.000881,-0.023728,-0.019843,0.010179,-0.018741,-0.025052,-0.018694,-0.021369,0.014646,0.010252,0.016849
2019-10-07,0.060214,0.088969,0.049167,0.051839,0.032106,0.020807,0.047681,0.044203,0.059294,0.107409,-0.006695,-0.002543,0.070329

In [7]:
# TODO: Add a KPI to measure how much the model worked

In [8]:
clusters_df = mc.load_clusters_data(
    return_df, 
    update=True
)
clusters_number = clusters_df['cluster'].unique().shape[0]
print(clusters_number, 'clusters')
clusters_df.head()

Clusters data file saved.
3 clusters

  symbol cluster
0   DOGE       0
1    ADA       1
2   ATOM       1
3    BCH       1
4    BNB       1

# Regression Model

In [9]:
# TODO: Test should be in a range of time?
# TODO: Use ANN models
# TODO: Add financial indexes to regression model
# TODO: Add more regression models (LogisticRegression(), SVC(kernel='poly', probability=True), XGBClassifier(), etc)
# TODO: Grid search over parameters

In [10]:
normalized_df = dp.load_normalized_data(
    filtered_df, 
    clusters_df, 
    future_days=FUTURE_DAYS
)
print(normalized_df.shape)
normalized_df.head()

(18980, 47)

,symbol,cluster,date,open,high,low,close,avg,return,volume,...,symbol_MATIC,symbol_TRX,symbol_USDC,symbol_USDT,symbol_XRP,cluster_0,cluster_1,cluster_2,future_return,future_risk
0,BTC,1,2023-10-01,26967.397433,28047.237710,26965.094292,27983.750382,27475.573907,0.037688,9.503917e+09,...,False,False,False,False,False,False,True,False,NaN,NaN
1,BTC,1,2023-09-30,26911.689185,27091.795508,26888.967804,26967.916301,26939.802743,0.002089,5.331173e+09,...,False,False,False,False,False,False,True,False,NaN,NaN
2,BTC,1,2023-09-29,27024.841714,27225.938430,26721.762797,26911.721603,26968.281658,-0.004186,1.039644e+10,...,False,False,False,False,False,False,True,False,NaN,NaN
3,BTC,1,2023-09-28,26355.812395,27259.499223,26327.321712,27021.546765,26688.679580,0.025259,1.407900e+10,...,False,False,False,False,False,False,True,False,NaN,NaN
4,BTC,1,2023-09-27,26209.498349,26817.842315,26111.464382,26352.717619,26281.107984,0.005464,1.171838e+10,...,False,False,False,False,False,False,True,False,NaN,NaN

In [11]:
# normalized_df.plot.scatter(x='close', y='future_return')

In [12]:
regression_df = mc.load_regression_data(
    normalized_df, 
    model='random_forest_regressor', 
    update=True
)
print(regression_df.shape)
regression_df.head()

Train R2: 98.38%
Test R2: 93.15%
(13, 47)

,symbol,cluster,date,open,high,low,close,avg,return,volume,...,symbol_MATIC,symbol_TRX,symbol_USDC,symbol_USDT,symbol_XRP,cluster_0,cluster_1,cluster_2,future_return,future_risk
0,ADA,1,2023-10-01,0.254043,0.267471,0.254019,0.265895,0.259969,0.046654,1.650882e+08,...,False,False,False,False,False,False,True,False,0.087955,0.003454
1,ATOM,1,2023-10-01,7.240846,7.637910,7.190096,7.564339,7.402593,0.044676,6.454523e+07,...,False,False,False,False,False,False,True,False,0.357960,0.002700
2,BCH,1,2023-10-01,234.329055,244.581620,233.740145,242.191526,238.260290,0.033553,2.061971e+08,...,False,False,False,False,False,False,True,False,-0.096392,0.001509
3,BNB,1,2023-10-01,214.800317,219.133842,213.506513,218.047134,216.423725,0.015116,3.874081e+08,...,False,False,False,False,False,False,True,False,-0.014277,0.001201
4,BTC,1,2023-10-01,26967.397433,28047.237710,26965.094292,27983.750382,27475.573907,0.037688,9.503917e+09,...,False,False,False,False,False,False,True,False,-0.025524,0.001126

# Portfolio Selection

In [13]:
# TODO: Use clustering models like HRP
# TODO: Add CAPM Model
# TODO: Add Black-Litterman allocation?
# TODO: long and short? weight_bounds=(-1, 1)
# TODO: non-covariance models: sparse portfolio, minimum variance portfolio, etc

In [14]:
performance_df = dp.load_performance_data(
    historical_df,
    DATE,
    FUTURE_DAYS,
)
print(performance_df.shape)
performance_df.head()

(1159, 4)

  symbol       date         close    return
0    BTC 2023-12-01  38688.748361  0.025737
1    BTC 2023-11-30  37712.747772 -0.003919
2    BTC 2023-11-29  37858.494055  0.000856
3    BTC 2023-11-28  37831.086868  0.015654
4    BTC 2023-11-27  37254.168854 -0.005340

In [15]:
dominated_df = mc.load_dominated_data(regression_df)
print(dominated_df.shape)
dominated_df.head()

(6, 4)

  symbol cluster  future_return  future_risk
0   DOGE       0       0.263549     0.003179
1   ATOM       1       0.357960     0.002700
2    LTC       1       0.167626     0.001805
3    BNB       1      -0.014277     0.001201
4    BTC       1      -0.025524     0.001126

In [16]:
portfolio_df = mc.load_ew_portfolio(dominated_df)
print(portfolio_df.shape)
portfolio_df.head()

(6, 2)

  symbol    weight
0   DOGE  0.166667
1   ATOM  0.166667
2    LTC  0.166667
3    BNB  0.166667
4    BTC  0.166667

In [17]:
sharpe_ratio = mc.get_portfolio_performance(portfolio_df, performance_df)
print(f"The Sharpe Ratio for your portfolio is {sharpe_ratio:.2f}.")

The Sharpe Ratio for your portfolio is 0.18.

In [18]:
close_df = dp.load_close_data(
    filtered_df, 
)
print(close_df.shape)
close_df.head()

(1460, 13)

,ADA,ATOM,BCH,BNB,BTC,DOGE,ETH,LTC,MATIC,TRX,USDC,USDT,XRP
date,,,,,,,,,,,,,
2019-10-03,0.038361,2.581556,222.579086,15.726760,8259.991979,0.002325,175.199341,56.546815,0.010669,0.014355,1.002371,1.004948,0.247860
2019-10-04,0.039667,2.586070,223.250807,15.755114,8205.939241,0.002360,176.985007,56.853212,0.010716,0.014708,1.005407,1.008841,0.253935
2019-10-05,0.039730,2.746641,223.165342,15.723580,8151.500529,0.002322,176.351523,56.843872,0.010591,0.015113,0.998863,1.001932,0.253457
2019-10-06,0.039324,2.666873,223.411925,15.348980,7988.155959,0.002346,173.059145,55.411569,0.010389,0.014789,1.013547,1.012087,0.257705
2019-10-07,0.041672,2.909280,234.236180,16.134346,8245.622933,0.002390,181.186333,57.788300,0.010999,0.016355,1.005492,1.008524,0.275685

In [19]:
# Mean Variance Max Sharpe

portfolio_df = mc.load_portfolio_with("mv", close_df)
sharpe_ratio = mc.get_portfolio_performance(portfolio_df, performance_df)
print(f"The Sharpe Ratio for your portfolio is {sharpe_ratio:.2f}.")

Expected annual return: 81.1%
Annual volatility: 90.9%
Sharpe Ratio: 0.87
The Sharpe Ratio for your portfolio is 0.18.

In [20]:
# Hierarchical Risk Parity

portfolio_df = mc.load_portfolio_with("hrp", close_df)
sharpe_ratio = mc.get_portfolio_performance(portfolio_df, performance_df)
print(f"The Sharpe Ratio for your portfolio is {sharpe_ratio:.2f}.")

Expected annual return: 0.6%
Annual volatility: 4.5%
Sharpe Ratio: -0.31
The Sharpe Ratio for your portfolio is 0.11.

In [21]:
# mCVAR

portfolio_df = mc.load_portfolio_with("mcvar", close_df)
sharpe_ratio = mc.get_portfolio_performance(portfolio_df, performance_df)
print(f"The Sharpe Ratio for your portfolio is {sharpe_ratio:.2f}.")

Expected annual return: -0.1%
Conditional Value at Risk: -0.00%
The Sharpe Ratio for your portfolio is -0.01.

In [22]:
# sparse portfolio

import numpy as np

# Extract the columns of interest
symbols = regression_df["symbol"]
returns = regression_df["future_return"].to_numpy()
risks = regression_df["future_risk"].to_numpy()

# Define the portfolio risk function
def portfolio_risk(w):
    return 0.5 * w.T @ np.diag(risks) @ w
# Define the portfolio return function
def portfolio_return(w):
    return w.T @ returns
# Define the gradient of the portfolio risk function
def portfolio_risk_grad(w):
    return np.diag(risks) @ w
# Define the projection onto the simplex
def project_simplex(w):
    u = np.sort(w)[::-1]
    cssv = np.cumsum(u)
    rho = np.nonzero(u * np.arange(1, len(u) + 1) > (cssv - 1))[0][-1]
    theta = (cssv[rho] - 1) / (rho + 1.0)
    return np.maximum(w - theta, 0)
# Define the thresholding operator
def threshold(w, k):
    idx = np.argsort(w)[::-1][:k]
    w_new = np.zeros_like(w)
    w_new[idx] = w[idx]
    return w_new

# Set the number of non-zero weights (e.g. 10)
k = 10
# Set the target portfolio return (e.g. 0.05)
r = 0.001
# Set the initial portfolio weights (e.g. uniform)
w = np.ones(len(symbols)) / len(symbols)
# Set the step size for gradient descent (e.g. 0.01)
alpha = 0.01
# Set the tolerance for convergence (e.g. 1e-6)
tol = 1e-6
# Set the maximum number of iterations (e.g. 1000)
max_iter = 10000
# Initialize the iteration counter and the convergence flag
iter = 0
converged = False
# Run the algorithm until convergence or maximum iterations
while not converged and iter < max_iter:
    # Save the current weights
    w_old = w.copy()
    # Update the weights using gradient descent
    w = w - alpha * portfolio_risk_grad(w)
    # Project the weights onto the simplex
    w = project_simplex(w)
    # Threshold the weights to enforce sparsity
    w = threshold(w, k)
    # Check the portfolio return constraint
    if portfolio_return(w) < r:
        # If violated, reset the weights to the previous ones
        w = w_old.copy()
        # Reduce the step size
        alpha = alpha / 2
    # Increment the iteration counter
    iter += 1
    # Check the convergence criterion
    if np.linalg.norm(w - w_old) < tol:
        # If satisfied, set the convergence flag to True
        converged = True
# Get the portfolio return and risk
portfolio_return = portfolio_return(w)
portfolio_risk = portfolio_risk(w)
# Print the results
print("The optimal sparse portfolio consists of the following stocks:")
cleaned_weights = {}
for i in range(len(symbols)):
    if w[i] > 0:
        print(f"{symbols[i]}: {w[i]:.2f}")
        cleaned_weights[symbols[i]] = round(w[i], 5)
print(f"The portfolio return is {portfolio_return:.4f} and the portfolio risk is {portfolio_risk:.4f}")

portfolio_df = dp.get_portfolio_from_dict(dict(cleaned_weights))
sharpe_ratio = mc.get_portfolio_performance(portfolio_df, performance_df)
print(f"The Sharpe Ratio for your portfolio is {sharpe_ratio:.2f}.")

The optimal sparse portfolio consists of the following stocks:
ATOM: 0.09
BCH: 0.10
BNB: 0.10
BTC: 0.10
DOGE: 0.08
ETH: 0.10
LTC: 0.10
TRX: 0.10
USDC: 0.11
USDT: 0.11
The portfolio return is 0.0255 and the portfolio risk is 0.0001
The Sharpe Ratio for your portfolio is 0.16.